### PR TITLE
Add MODS>DataCite mappings for form

### PR DESCRIPTION
**Pull request by arcadiafalcone**
## Why was this change made?
Partially addresses https://github.com/sul-dlss/happy-heron/issues/1908

## How was this change tested?
CircleCI

## Which documentation and/or configurations were updated?
n/a

### CODE REVIEW

**Review by jcoyne — CHANGES_REQUESTED** [review]
I think there's a misunderstanding here @arcadiafalcone. This is testing a mapping between cocina and datacite.  There isn't any MODS involved in this transformation.

**Comment by arcadiafalcone** [comment]
@jcoyne I was going off of this convo yesterday: https://stanfordlib.slack.com/archives/C69UZCJ8M/p1628535051337200

**Comment by jcoyne** [comment]
@arcadiafalcone I'm sorry, I didn't have a full understanding of what you were asking there. We need h2>cocina>mods and mods > cocina > datacite-json.  That latter can be decomposed into mods > cocina (which is already done) and cocina > datacite-json (which I belive is partially done)

**Comment by arcadiafalcone** [comment]
@jcoyne Thanks, that clarifies matters. I hadn't realized that the DataCite was coming out of cocina roundtripped from MODS.

**Pull request closed without merging**
