### PR TITLE
Use committee middleware to verify requests using OpenAPI

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

This uses the spec for validating requests instead of it just being for documentation. This ensures our documentation is up to date and accurate

## Was the API documentation (openapi.json) updated?

Yes

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@jcoyne We are waiting for a sniff test in stage from @andrewjbtw, right?

**Comment by jcoyne** [comment]
@mjgiarlo I think he already did that

**Comment by jcoyne** [comment]
@mjgiarlo https://stanfordlib.slack.com/archives/C09M7P91R/p1576011571085200

**Comment by andrewjbtw** [comment]
I don't think I finished that because we ended up reverting stage so I could continue to test virtual objects. I don't know if this was redeployed to stage for the rest of last week. See the discussion at https://stanfordlib.slack.com/archives/C09M7P91R/p1576082583108500

**Comment by jcoyne** [comment]
@andrewjbtw okay, rebased and deployed to stage. Test away.

**Comment by mjgiarlo** [comment]
@jcoyne once @andrewjbtw gives the high sign, feel free to merge

**Pull request merged**
