### PR TITLE
Update H2-Cocina-MODS event mapping to match H2 output

### PR DESCRIPTION
**Pull request by arcadiafalcone**
## Why was this change made?
H2 can't currently provide some of the data the mapping expected

## How was this change tested?
CircleCI

## Which documentation and/or configurations were updated?
n/a

### CODE REVIEW

**Review by ndushay — APPROVED** [review]

**Comment by jcoyne** [comment]
Is there a reason we chose this route over updating h2 to provide the necessary format?

**Comment by arcadiafalcone** [comment]
When I last raised the issue, there was a desire to keep H2 dates encoded as edtf, though in practice they are identical to w3cdtf.

**Comment by jcoyne** [comment]
I think we want to keep h2 dates encoded as edtf in the database, but we could make the cocina data that h2 exports to SDR map to usew3cdtf.

**Comment by arcadiafalcone** [comment]
Yes, we're not actually using any of the edtf-specific encodings, and our systems aren't set up to parse them anyway. I think it's fine to keep them as edtf - they appear to be displaying correctly, and LC has moved towards preferring it.

**Pull request merged**
