### PR TITLE
deal with special characters in title from any location

### LINKED ISSUE #201: Need to XML encode title in goobi request
Special characters in the title block when coming from sources other than DOR will cause improper XML when posting to the goobi URL

e.g. https://argo.stanford.edu/view/druid:wt905dd4835

### PR DESCRIPTION
**Pull request by peetucket**
fixes #201 

- [x] improve tests to confirm escaping occurs with both MODs and fedora labels

### CODE REVIEW

**Comment by peetucket** [comment]
Thanks, yes switched to WIP since I'm going to try and make the test more robust to ensure the escaping of special character occurs regardless of title source (MODs vs fedora label).  The bug before was the it was occurring in one case but not the other.  Expect to have that done soon, then would appreciate another quick look.

**Comment by jmartin-sul** [comment]
@peetucket feel free to ping here on on slack whenever it's ready

**Comment by jcoyne** [comment]
@peetucket have you heard about Draft pull requests?  They're a brand new way to share your wip: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by peetucket** [comment]
> @peetucket have you heard about Draft pull requests? They're a brand new way to share your wip: https://github.blog/2019-02-14-introducing-draft-pull-requests/

Yeah, but didn't see a way to convert a regular PR to a WIP (I started as a regular PR, then changed my mind and wanted to add another test).

**Pull request merged**
