### PR TITLE
bump to dor-services 4.22 and dor-workflow-service to 1.7.7

### PR DESCRIPTION
**Pull request by drh-stanford**
Note that you have to install oracle for this to install. the dev box already has it installed (see config/deploy.rb). I added a .travis.yml, but it doesn't work because travis does not support Oracle.

### CODE REVIEW

**Comment by tingulfsen** [comment]
Thanks for doing this, just one question - why the version specification for pry-debugger?

**Comment by atz** [comment]
Debuggers shouldn't need to be included as dependencies at all, let alone pinned to a specific version... only for one version of ruby.

**Comment by tingulfsen** [comment]
Joe, can you be a bit more specific? What is the problem with including debuggers in the Gemfile?

**Comment by drh-stanford** [comment]
I got the pin from here https://github.com/sul-dlss/dor-services/blob/develop/Gemfile#L5

**Comment by drh-stanford** [comment]
@atz @tingulfsen should I take out the debugger pin? and if so, should we also take it our of dor-services? thanks.

**Comment by tingulfsen** [comment]
I have to admit that I'm not quite sure what @atz is referring to, so I'd like to wait for his response if you don't mind.

**Comment by drh-stanford** [comment]
moved travis config to https://github.com/sul-dlss/dor-services-app/pull/7

**Comment by tingulfsen** [comment]
@drh-stanford, I've spoken to @atz, and the rationale for not referencing debuggers in the dependencies is that there shouldn't be any code that needs the debugger to run and that we want to minimize the number of dependencies. Could you remove the debugger dependency, but leave a comment stating what the preferred debugger version is? I think you could just comment out that one line in the Gemfile. Thanks!

**Comment by drh-stanford** [comment]
ok i snipped that out and updated the `Gemfile.lock`

**Pull request merged**
