### PR TITLE
updated abstract mapping

### LINKED ISSUE #2728: Implement updated abstract specs
See #2727 

#2772 should be merged before working on this ticket.

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made?

Fixes #2728  - updated abstract mapping

Note that a number of other tests had to be updated to reflect the updated mappings, see https://github.com/sul-dlss/dor-services-app/issues/2728#issuecomment-833898287

## How was this change tested?

Unskipped tests in #2727 and updated other existing tests as needed with Arcadia's approval.

### CODE REVIEW

**Comment by peetucket** [comment]
Ok, finally got everything passing with a new normalization to downcase abstract types.

@arcadiafalcone and @justinlittman

**Comment by jcoyne** [comment]
Should this be tested with `bin/validate-desc-cocina-roundtrip -s 100000`?

**Comment by peetucket** [comment]
> bin/validate-desc-cocina-roundtrip -s 100000

Good idea.  Ran with these top level stats:

```
Testing |Time: 00:11:25 | ========================================================================================= | Time: 00:11:25
Status (n=100000; not using Missing for success/different/error stats):
  Success:   98690 (99.116%)
  Different: 880 (0.884%)
  To Cocina error:     0 (0.0%)
  To Fedora error:     0 (0.0%)
  MODS normalizer error:     0 (0.0%)
  Missing (no descMetadata):     430 (0.43%)
```

**Comment by jcoyne** [comment]
@peetucket can you post a baseline from the main branch too.  It seems to me there may be a regression here.

**Comment by peetucket** [comment]
Ok, after examining some of the diffs, I made a small change to the PR and re-ran the validation again, and it's looking much better:

```
Testing |Time: 00:05:12 | ========================================================================================= | Time: 00:05:12
Status (n=100000; not using Missing for success/different/error stats):
  Success:   99538 (99.968%)
  Different: 32 (0.032%)
  To Cocina error:     0 (0.0%)
  To Fedora error:     0 (0.0%)
  MODS normalizer error:     0 (0.0%)
  Missing (no descMetadata):     430 (0.43%)
```

**Comment by peetucket** [comment]
And spotted another small change I need to make...

Let me make a couple changes and see if I can add another test to catch what I missed.  Will switch PR back to draft .

**Comment by peetucket** [comment]
Latest results after working on this branch:

```
Status (n=100000; not using Missing for success/different/error stats):
  Success:   99562 (99.992%)
  Different: 8 (0.008%)
  To Cocina error:     0 (0.0%)
  To Fedora error:     0 (0.0%)
  MODS normalizer error:     0 (0.0%)
  Missing (no descMetadata):     430 (0.43%)
```

A look at those 8 suggest none are related to notes/abstracts worked on here.  

Ran another random sample of 100k and got a similar result.

**Review by jcoyne — APPROVED** [review]

**Pull request merged**
