### PR TITLE
Add SDR service gateway endpoints

### PR DESCRIPTION
**Pull request by cbeer**
This allows the dor-services-app to mediate requests to the SDR services, instead of requiring all dor-services consumers to get special access to SDR. There will be a corresponding change in dor-services to consume these endpoints instead of accessing SDR directly.

### CODE REVIEW

**Comment by darrenleeweber** [comment]
Seems :+1: when dependencies are resolved and specs are passing.

**Comment by darrenleeweber** [comment]
Oh, tests still failing.

**Comment by cbeer** [comment]
Yes, it depends on a new dor-services release.

**Comment by darrenleeweber** [comment]
https://github.com/sul-dlss/dor-services/pull/163 is merged, update this now?

**Comment by cbeer** [comment]
But not released.

**Pull request merged**
