### PR TITLE
Adds support for performing cocina migrations.

### PR DESCRIPTION
**Pull request by justinlittman**
refs #4349

## Why was this change made? 🤔
Provide framework for performing cocina data migrations.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

sdr-infra

### CODE REVIEW

**Review by ndushay — COMMENTED** [review]
Given that we are likely going to be migrating cocina data from time to time, it seems sensible to write much of the code in a ?? service ?? class and have the rake task be skinny.  This would allow for test code, no?

**Comment by justinlittman** [comment]
With this approach, the logic of the migration is in the Migrator::* class, which can be tested. The mechanics of the migration are in the executable script.

**Review by peetucket — APPROVED** [review]

**Review by ndushay — COMMENTED** [review]
I'm sorry I didn't get to reviewing this yesterday.

A few thoughts, belatedly:
1.  "exemplar" is a better name for the test class you wrote;  "test" is an overloaded term
2.  For base class, add the comments that are obious to you:
- "override this method for ..."
3.  have specs for what happens when you do and don't override "publish" and "version" and "version_description"

Would you like me to put up a quick PR for these?

**Comment by justinlittman** [comment]
Sure, since the proposed changes are probably clearer to you.

**Pull request merged**
