### PR TITLE
[hold] Remove unused DateTimeValidator

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made? 🤔
It's not used.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

### CODE REVIEW

**Review by justinlittman — CHANGES_REQUESTED** [review]
It will be used for upcoming DateTime validation (but will probably need to move to cocina models). Can we leave for now?

**Comment by ndushay** [comment]
there are plans afoot for date validation; does this imply this PR should be closed?

**Comment by ndushay** [comment]
or maybe this should be closed because it's now in cocina-models??

**Comment by justinlittman** [comment]
It hasn't been moved yet; it is still in DSA.

**Comment by ndushay** [comment]
It's possible we want to keep the regex code, or change the reports to use the regexps in cocina-models ...

**Comment by mjgiarlo** [comment]
Done in #4091. I believe this can be closed now, @jcoyne

**Comment by ndushay** [comment]
closing this as Mike took care of it in #4091

**Pull request closed without merging**
